# Generated by Django 4.2.1 on 2023-05-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel_mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest', models.CharField(max_length=50)),
                ('desc', models.TextField(max_length=80)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Viewtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField(max_length=80)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(default='null.jpg', upload_to='images')),
            ],
        ),
    ]
