# Generated by Django 4.2.1 on 2023-05-31 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=40)),
                ('contact', models.IntegerField()),
                ('password', models.CharField(max_length=15)),
                ('confirm_password', models.CharField(max_length=15)),
            ],
        ),
    ]
